# Generated by Django 5.2.4 on 2025-08-08 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logisticsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='quote',
            new_name='quotes',
        ),
    ]
