# Generated by Django 5.2.4 on 2025-08-08 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logisticsapp', '0002_rename_quote_quotes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='quotes',
            new_name='quote',
        ),
    ]
